# Generated by Django 4.1.5 on 2023-01-17 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_integrantes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Integrantes',
        ),
    ]
