# Generated by Django 4.1.3 on 2023-01-19 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_integrantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrantes',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre y apellidos')),
                ('carnet_ident', models.PositiveIntegerField(default=0)),
                ('trabaja', models.BooleanField(default=False, verbose_name='Trabaja')),
                ('estudia', models.BooleanField(default=False, verbose_name='Estudia')),
                ('desocupado', models.BooleanField(default=False, verbose_name='Desocupado')),
                ('centro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Centro de estudio o trabajo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.integrantes')),
            ],
        ),
    ]
